### ISSUE TITLE
mega menu submenu width

### ISSUE THREAD

**Issue by michellomp** [SimonPadbury/WBST#2]
Hi 
I've installed your starter theme and i have a probleme with the width of the submenu in mega menu.
I only have three columns in my mega menu so there's some blank space in the right of the menu.
Do you know how could i do for the mega menu to have 1/3 width for each submenu

Thanks

**Comment by SimonPadbury** [comment]
Hi

A simple way to do this is to add some &nbsp; after the child menu item title, within the WordPress menu builder. each column is as wide as the menu item with the biggest title.

Except for doing what I suggest above, it would probably require some JavaScript to calculate the column widths required to fill the 100% mega menu drop down, because I can't know how wide each user requires his columns to be, or how many columns he needs.

Hope this helps.

Simon
