### ISSUE TITLE
Sub menus are full-width

### ISSUE THREAD

**Issue by mentolnet** [SimonPadbury/WBST#3]
Hello.
The dropdown menu now has full width sublinks. Is this correct?

**Comment by SimonPadbury** [comment]
Hello Mentolnet,

In WBST there is an _optional_ mega-menu -- if you don't like this, simply delete the **meganav** code in the `bst.js` and the `bst.css`. (Similarly, the menus drop down on hover -- this is optional too -- you can delete **hovernav** from the `bst.js` and the `bst.css`). I did not modify Bootstrap itself.

If you have navbar 'children' dropdowns, then the dropdown happens in the normal Bootstrap way:

```
... Parent 1 ...
    Child 1a
    Child 1b
    Child 1c
```

Remember, Bootstrap navbar does not allow 'grandchildren' links. But **meganav** does allow -- by creating a full-width menu (a mega-menu). The 'child' links are rendered bold.

```
... Parent 1 ...
    Child 1a             Child 1b             Child 1c
    Grandchild 1ai       Grandchild 1bi       Grandchild 1ci 
    Grandchild 1aii      Grandchild 1bii      Grandchild 1cii 
    Grandchild 1aiii     Grandchild 1biii     Grandchild 1ciii 
```

I added this **meganav** because some people need to create big WooCommerce shops with many items in different 'departments' or categories. Example

[https://econsultancy.com/blog/65357-mega-menu-design-trends-in-ecommerce-2011-vs-2014/](https://econsultancy.com/blog/65357-mega-menu-design-trends-in-ecommerce-2011-vs-2014/)

If you don't need this, delete it, as I describe above.

Enjoy!

Simon

**Comment by mentolnet** [comment]
Hi there.
Yes, i had the feeling that it had something to do with the megamenu. Nonetheless, i had my doubts because i had my navigation menu assigned to the upper navbar (right) and the links appear all the way to the left, close to the limit of the browser window. I understand that this is because this navbar is full-width but it doesn´t really seems quite right visually.
I then changed my navigation to the lower navbar (right) and it makes more sense visually, even if the main links are on the right and the child and grandchild links go all the way to the left.
Again, i understand that this is a framework with minimum styling (and i´ve been using bst for a couple of projects), but do you have any advice regarding how to use the megamenu if i want also to have the navigation on the right, especially if the main menu doesn´t have a lot of links?
I am attaching an image to better illustrate this matter. Thank you for your work with this.

All the best.

Screengrab: http://pho.to/9o5q5

**Comment by mentolnet** [comment]
Hi there.
Yes, i had the feeling that it had something to do with the megamenu. Nonetheless, i had my doubts because i had my navigation menu assigned to the upper navbar (right) and the links appear all the way to the left, close to the limit of the browser window. I understand that this is because this navbar is full-width but it doesn´t really seems quite right visually.
I then changed my navigation to the lower navbar (right) and it makes more sense visually, even if the main links are on the right and the child and grandchild links go all the way to the left.
Again, i understand that this is a framework with minimum styling (and i´ve been using bst for a couple of projects), but do you have any advice regarding how to use the megamenu if i want also to have the navigation on the right, especially if the main menu doesn´t have a lot of links?
I am attaching an image to better illustrate this matter. Thank you for your work with this.

All the best.

Screengrab: http://pho.to/9o5q5

**Comment by SimonPadbury** [comment]
Hi,

No I don't know how to do this, because (a) I can't know/calculate where the left edge of your dropdown will be (this depends on position of its parent link), and (b) I can't know/calculate where the right edge or your dropdown will be (this depends on the number of columns in the mega dropdown; plus you will need to stop it going off the right edge of the screen). Probably this can be done from a zero-start (not starting with Bootstrap `.navbar`). Buy my **meganav** is only a simple override of Bootstrap. It is useful of you have lots of child 'columns', but not if you only have a few.

Maybe you can forget the Bootstrap `.navbar` and use one of these instead:

[http://www.maxmegamenu.com](http://www.maxmegamenu.com)

[http://www.designchemical.com/blog/index.php/tutorials/wordpress-tutorial-create-your-own-custom-mega-menu-styles/](http://www.designchemical.com/blog/index.php/tutorials/wordpress-tutorial-create-your-own-custom-mega-menu-styles/)

[http://www.wpfreeware.com/tutorial/wordpress-mega-menu-plugins-for-better-navigation/](http://www.wpfreeware.com/tutorial/wordpress-mega-menu-plugins-for-better-navigation/)

**Comment by mentolnet** [comment]
Hello Simon and thank you again for your answer and examples.
I´ll give them some attention and see if i can manage this.

All the best!

**Comment by SimonPadbury** [comment]
Thanks. Sorry I couldn't be of more help.
